### ISSUE TITLE
No VKB device found?

### ISSUE THREAD

**Issue by DarthJahus** [tiberiusteng/vkb-msfs-led#1]
Hello,

After preparing the script and running it, I get this error. It seems that the script is not detecting the VKB device.

```
    ext = find_all_vkb()[0]
IndexError: list index out of range
```

I have also opened [an issue](https://github.com/ventorvar/pyvkb/issues/4#issue-1128871675) on `pyvkb`, since even `vkb list` doesn't show devices.

**Comment by tiberiusteng** [comment]
Hi,

Seems VKBDevCfg would generate different USB device IDs for different combination of modules (and even for different  configurations), so you can try running VKBDevCfg to see what product ID has been assigned to your device, and modify the ID in `nxtext.py` accordingly.

**Comment by DarthJahus** [comment]
Thank you for your answer, as it helped me track down the issue and fix it. I have added a class in `nxtext.py` with my product ID, which was indeed different (`0x0234` instead of `0x2234`), and added a definition in `vkb_device_init.py` for the new device (then copied it and replaced `__init__.py` in `Lib\site-packages\vkb\devices`.

Now my device gets recognized! Yay! Can't wait to tinker with the script and see all what can be done. Tested with a Cessna 208B and it works amazingly 😍 You did a great job. Thank you!

---

As for PyVKB package, I have discovered, while investigating the issue, that there was a new version, more recent than the one in PyPi (that you get through `pip`). However, your script doesn't work with the new version, as I believe it will need some tweaks. For instance, I have got a TypeError.

```
  File "C:\Users\Jahus\Desktop\VKB\vkb-msfs-led\lib\site-packages\vkb\contrib\dinput.py", line 628, in _init_directinput
    IID_IDirectInput8W, ctypes.byref(dinput), None)
TypeError: byref() argument must be a ctypes instance, not 'IDirectInput8'
```

If @[ventorvar](https://github.com/ventorvar) updates the package, you might want to do the same with the LED script (you can check the referenced issue on PyVKB for discussion).

Feel free to close this issue. Thanks again!
