### ISSUE TITLE
Coding question

### ISSUE THREAD

**Issue by WesCov** [tiberiusteng/vkb-msfs-led#2]
Could I ask you to explain how one of your functions is working?

def find_all_vkb():
    devices = []
    for pid, cls in VKB_DEVICES.items():
        devices.extend(
            cls(_)
            for _ in hid.HidDeviceFilter(
                vendor_id=cls.VENDOR_ID, product_id=pid
            ).get_devices()
        )
    return sorted(devices, key=lambda d: d.guid)

The .extend command seems to merge the device information with the current object in the loop.  cls is the current object pulled from the dictionary; what does the "cls(_) for _ in..." do?   I want to do the same thing but for a specific product (given vendor and product ids) but I don't know how this code integrates the device info into the class...  Does it trigger the init or something?  Very clever and unique -- I haven't been able to find any one else doing this.

**Comment by tiberiusteng** [comment]
```
for pid, cls in VKB_DEVICES.items():
	for device in hid.HidDeviceFilter(vendor_id=VENDOR_ID, product_id=pid).get_devices():
		cls(device)
```
above is the code rewrite in another format; it's getting the device object with HidDeviceFilter, call constructor of a class derived from VKBDevice and pass the device object to it. refer to the base class at https://github.com/ventorvar/pyvkb/blob/master/vkb/devices/base.py#L12

**Comment by WesCov** [comment]
Thank you very much.  The extend() and cls(_) combination was confusing me.  This example helps a lot.
