### ISSUE TITLE
get_led_configs() or LEDConfig.frombytes() has the led_mode for the last LED as 0

### ISSUE THREAD

**Issue by WesCov** [tiberiusteng/vkb-msfs-led#3]
When setting more than 1 LED and then getting the settings, the last LED has the led_mode set to 0.  I can't figure our why it works for 1 LED, but not for 2+.  Do you know why that would happen?

**Comment by tiberiusteng** [comment]
Hi, currently I don't have hardware at my hand so I can't validate the hardware behavior, but if I remembers correctly when I wrote the code I'm encountered exactly the same situation as yours, that is, it does not correctly report back its current status. (or we just don't know how to correctly decode it). I would suggest you separately track the current status and only send new lighting instructions to the hardware.

**Comment by WesCov** [comment]
Thank you for your reply.  I did read the note in the code but I thought that there was a solution there and I just didn't understand it.  My plan to side step the issue is to always add a "dummy" led in the last position.  A dummy doesn't affect the flight stick and the error will be absorbed & then ignored.  Thanks again.
